# starship prompt configuration
# Updated 2020-11-10.
# https://starship.rs/config/

add_newline = true

[aws]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_length = 4
truncation_symbol = ""

[gcloud]
disabled = true

[python]
python_binary = "python3"
