# """
# starship prompt configuration
# Updated 2021-02-15.
#
# Allowed colors: black, blue, cyan, green, purple, red, white, yellow.
# Note that magenta is not currently supported.
# Colors are documented in the advanced configuration section.
#
# See also:
# - https://starship.rs/config/
# - https://starship.rs/advanced-config/
# """

add_newline = true
# > format = "$all"

[aws]
disabled = true

[cmd_duration]
disabled = true

# > [character]
# > error_symbol = "[✗](bold red)"
# > success_symbol = "[❯](bold green)"

[directory]
# > style = "bold cyan"
read_only = ""
read_only_style = "yellow"
style = "blue"
truncate_to_repo = false
truncation_length = 0  # no truncation
truncation_symbol = ""

[gcloud]
disabled = true

[hostname]
format = "[$hostname]($style)\n"
ssh_only = false
style = "cyan"
trim_at = "."

# Note that this will activate when calling 'bash -il' inside Zsh.
[jobs]
symbol = "+"
threshold = 1

[python]
python_binary = "python3"

[username]
format = "[$user]($style)[@](cyan)"
show_always = true
style_root = "bold yellow"
style_user = "cyan"
