# """
# starship prompt configuration
# Updated 2021-06-21.
#
# Allowed colors: black, blue, cyan, green, purple, red, white, yellow.
# Note that "magenta" maps to "purple" here.
# Colors are documented in the advanced configuration section.
#
# See also:
# - https://starship.rs/config/
# - https://starship.rs/advanced-config/
# """

add_newline = true
# > format = "$all"
# The default of 500ms sometimes generates warnings with large Git repos.
command_timeout = 2000
scan_timeout = 30

[aws]
disabled = true

[cmd_duration]
disabled = true

[character]
disabled = false
error_symbol = "[✗](bold red)"
success_symbol = "[❯](purple)"

[directory]
# > style = "bold cyan"
read_only = ""
read_only_style = "yellow"
style = "blue"
truncate_to_repo = false
truncation_length = 0  # no truncation
truncation_symbol = ""

# [env_var]
# disabled = false
# format = "[subshell]($style) "
# style = "yellow"
# variable = "KOOPA_SUBSHELL"

[gcloud]
disabled = true

[git_branch]
always_show_remote = false
format = "[$branch]($style) "
style = "green"

[git_status]
style = "bold red"

[hostname]
format = "[$hostname]($style)\n"
ssh_only = false
style = "cyan"
trim_at = "."

# Note that this will activate when calling 'bash -il' inside Zsh.
[jobs]
symbol = "+"
threshold = 1

[lua]
disabled = true

[python]
python_binary = "python3"

# Don't show the module when '~/.Rprofile' is detected.
[rlang]
detect_extensions = ["R", "Rd", "Rmd", "Rproj"]
detect_files = [""]
detect_folders = [".Rproj.user"]
symbol = "R"

# Assuming Zsh is default shell.
[shell]
bash_indicator = "\\$ "
disabled = false
format = "$indicator"
zsh_indicator = ""

[username]
format = "[$user]($style)[@](cyan)"
show_always = true
style_root = "bold yellow"
style_user = "cyan"
