#!/usr/bin/sh

# bcbio
export BCBIO_EXE="/data00/bcbio/v1.1.5/tools/bin/bcbio_nextgen.py"

# koopa shell
# https://github.com/acidgenomics/koopa/
# shellcheck source=/dev/null
extra=1 . "${HOME}/.koopa/activate.sh"
