#!/usr/bin/sh

# bcbio
export BCBIO_EXE="/data00/bcbio/v1.1.3/tools/bin/bcbio_nextgen.py"

# koopa shell
# https://github.com/acidgenomics/koopa/
# shellcheck source=/dev/null
extra=1 . "${HOME}/.koopa/activate.sh"

# Work on integrating this into koopa.
export VIRTUAL_ENV_DISABLE_PROMPT=1
source ~/.virtualenvs/default/bin/activate

# Launch a new tmux session automatically.
if [ ! -n "${TMUX:-}" ]
then
    tmux new
fi
