#!/usr/bin/env bash
set -Eeu -o pipefail

export KOOPA_CHECKS=0
# shellcheck source=/dev/null
source "$(koopa header bash)"
prefix="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"

link() {
    koopa::link_dotfile "$@"
}

install() {
    local name_fancy
    name_fancy='dotfiles'
    koopa::install_start "$name_fancy"
    expected_prefix="$(koopa::dotfiles_prefix)"
    koopa::assert_are_identical \
        "$(koopa::realpath "$prefix")" \
        "$(koopa::realpath "$expected_prefix")"
    koopa::add_config_link "$prefix" 'dotfiles'
    koopa::rm \
        "${HOME}/.R/Makevars" \
        "${HOME}/.config/doom" \
        "${HOME}/.kshrc" \
        "${HOME}/.oh-my-zsh" \
        "${HOME}/.shrc" \
        "${HOME}/.tmux" \
        "${HOME}/.zprofile"
    link --force --config 'app/broot'
    link --force --config 'app/hadolint/hadolint.yaml' 'hadolint.yaml'
    link --force --config 'app/htop'
    link --force --config 'app/neofetch'
    link --force --config 'app/nvim'
    link --force --config 'app/pip'
    link --force --config 'app/ranger'
    link --force --config 'app/rstudio'
    link --force --config 'app/starship/starship.toml' 'starship.toml'
    link --force --config 'shell/fish'
    link --force --config 'shell/oil'
    link --force 'app/curl/curlrc'
    link --force 'app/editorconfig/editorconfig'
    link --force 'app/emacs/doom' 'doom.d'
    link --force 'app/emacs/spacemacs/spacemacs.el' 'spacemacs'
    link --force 'app/git/gitignore'
    link --force 'app/gnupg/dirmngr.conf' 'gnupg/dirmngr.conf'
    link --force 'app/npm/npmrc'
    link --force 'app/pylint/pylintrc'
    link --force 'app/python/pyrc'
    link --force 'app/screen/screenrc'
    link --force 'app/terminfo/terminfo.d' 'terminfo'
    link --force 'app/tmux/tmux.conf'
    # > link --force 'app/tmux/tmux.d' 'tmux'
    link --force 'app/vim/vim.d' 'vim'
    link --force 'app/vim/vimrc'
    link --force 'app/wget/wgetrc'
    link --force 'shell/bash/bash_logout'
    link --force 'shell/bash/bash_profile'
    link --force 'shell/bash/bashrc'
    link --force 'shell/bash/inputrc'
    link --force 'shell/posix/aliases'
    link --force 'shell/posix/profile'
    link --force 'shell/zsh/zlogout'
    link --force 'shell/zsh/zshrc'
    # Placeholder for using "main" instead of "master" for default git branch.
    # Inspired by https://github.com/mathiasbynens/dotfiles
    # > link --force --config 'app/git/template' 'git/template'
    if koopa::is_macos
    then
        link --force --config 'app/alacritty'
        link --force 'app/vim/gvimrc'
        link --force 'os/macos/app/gnupg/gpg-agent.conf' 'gnupg/gpg-agent.conf'
    else
        link --force 'app/gnupg/gpg-agent.conf' 'gnupg/gpg-agent.conf'
    fi
    if [[ -d "${HOME}/.gnupg" ]]
    then
        koopa::chmod 0700 "${HOME}/.gnupg"
    fi
    if [[ -d "${HOME}/.ssh" ]]
    then
        koopa::chmod 0700 "${HOME}/.ssh"
    fi
    koopa::install_success "$name_fancy"
    return 0
}

install "$@"
