#!/usr/bin/env bash
set -Eeu -o pipefail

# FIXME
set -x

# shellcheck source=/dev/null
checks=0 source "$(koopa header bash)"
prefix="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"

link() {
    koopa::link_dotfile "$@"
}

install() {
    local name_fancy
    name_fancy='dotfiles'
    koopa::install_start "$name_fancy"
    expected_prefix="$(_koopa_dotfiles_prefix)"
    koopa::assert_are_identical \
        "$(realpath "$prefix")" \
        "$(realpath "$expected_prefix")"
    koopa::add_config_link "$prefix"
    rm -frv "${HOME}/."{'R/Makevars','kshrc','oh-my-zsh','shrc','zprofile'}
    link --force --config 'app/emacs/doom/config.d' 'doom'
    link --force --config 'app/htop'
    link --force --config 'app/neofetch'
    link --force --config 'app/nvim'
    link --force --config 'shell/fish'
    link --force 'app/curl/curlrc'
    link --force 'app/editorconfig/editorconfig'
    link --force 'app/emacs/spacemacs/spacemacs.el' 'spacemacs'
    link --force 'app/git/gitignore'
    link --force 'app/gnupg/dirmngr.conf' 'gnupg/dirmngr.conf'
    link --force 'app/python/pylintrc'
    link --force 'app/screen/screenrc'
    link --force 'app/terminfo/terminfo.d' 'terminfo'
    link --force 'app/tmux/tmux.conf'
    link --force 'app/tmux/tmux.d' 'tmux'
    link --force 'app/vim/vim.d' 'vim'
    link --force 'app/vim/vimrc'
    link --force 'app/wget/wgetrc'
    link --force 'shell/bash/bash_logout'
    link --force 'shell/bash/bash_profile'
    link --force 'shell/bash/bashrc'
    link --force 'shell/bash/inputrc'
    link --force 'shell/posix/aliases'
    link --force 'shell/posix/profile'
    link --force 'shell/zsh/zlogout'
    link --force 'shell/zsh/zshrc'
    # Placeholder for using "main" instead of "master" for default git branch.
    # Inspired by https://github.com/mathiasbynens/dotfiles
    # > link --force --config 'app/git/template' 'git/template'
    if koopa::is_macos
    then
        link --force --config 'app/alacritty'
        link --force 'app/vim/gvimrc'
        link --force 'os/macos/app/gnupg/gpg-agent.conf' 'gnupg/gpg-agent.conf'
    else
        link --force 'app/gnupg/gpg-agent.conf' 'gnupg/gpg-agent.conf'
    fi
    [[ -d "${HOME}/.gnupg" ]] && chmod 0700 "${HOME}/.gnupg"
    [[ -d "${HOME}/.ssh" ]] && chmod 0700 "${HOME}/.ssh"
    koopa::install_success "$name_fancy"
    return 0
}

install "$@"
