#!/usr/bin/sh




# Shared POSIX-compatible shell configuration.
# Intended for bash and zsh.
# Don't attempt to use with fish or tcsh.
export SHRC=1



# Set default file permissions.
#
# - `umask`: Files and directories.
# - `fmask`: Only files.
# - `dmask`: Only directories.
#
# Use `umask -S` to return `u,g,o` values.
#
# - 0022: u=rwx,g=rx,o=rx
#         User can write, others can read. Usually default.
# - 0002: u=rwx,g=rwx,o=rx
#         User and group can write, others can read.
#         Recommended setting in a shared coding environment.
# - 0077: u=rwx,g=,o=
#         User alone can read/write. More secure.
#
# Access control lists (ACLs) are sometimes preferable to umask.
# Here's how to use ACLs with setfacl.
# setfacl -d -m group:name:rwx /dir
#
# See also:
# - https://stackoverflow.com/questions/13268796
# - https://askubuntu.com/questions/44534
umask 0002



# koopa shell
# https://github.com/steinbaugh/koopa
# shellcheck source=/dev/null
cmd="activate" . "${HOME}/.koopa/bin/koopa.sh"



# Set up the today bucket and symlink.
if [ "$USER" = "mike" ] || [ "$USER" = "michael.steinbaugh" ]
then
    bash today-bucket.sh
fi
