#!/bin/sh

# """
# POSIX aliases.
# @note Updated 2021-05-08.
# """

# Shortcuts {{{1
# ==============================================================================

alias c='clear'
alias e='exit'
alias h='history'
# shellcheck disable=SC2153
alias k='cd "${KOOPA_PREFIX:?}"; l'
alias ku='koopa update'
alias q='exit'
# > alias :q='exit'  # vim reflex

# Productivity {{{1
# ==============================================================================

[ -d "${HOME}/today" ] && alias bucket="cd ~/today; l"
alias today='date "+%Y-%m-%d"'
alias week='date "+%V"'

# Listing files {{{1
# ==============================================================================

if _koopa_is_installed exa
then
    # Use exa instead of ls, when possible.
    # https://the.exa.website/docs/command-line-options
    #
    # Useful exa flags:
    # * -F, --classify
    #         Displays file type indicators by file names.
    # * -a, --all
    #         Shows hidden and ‘dot’ files.
    #         Use this twice to also show the . and .. directories.
    # * -g, --group
    #         Lists each file’s group.
    # * -l, --long
    #         Displays files in a table along with their metadata.
    # * -s, --sort=SORT_FIELD
    #         Configures which field to sort by.
    # *     --git-ignore
    #         Ignores files mentioned in .gitignore.
    # *     --group-directories-first
    #         Lists directories before other files when sorting.
    alias l="exa  --classify --group --group-directories-first --sort='Name'"
    alias la='l --all'
    alias ll='la --long'
else
    # Otherwise fall back to system ls.
    #
    # Note that note all versions of ls support long flags.
    #
    # Useful ls flags:
    # * -B, --ignore-backups
    #         do not list implied entries ending with ~
    # * -F, --classify
    #         append indicator (one of */=>@|) to entries
    # * -h, --human-readable
    #         with -l and -s, print sizes like 1K 234M 2G etc.
    alias l='ls -BFh'
    alias la='l -a'
    alias ll='la -l'
fi
alias l.='l -d .*'
alias l1='ls -1'

# List head or tail.
alias lh='l | head'
alias lt='l | tail'

# Clear then list.
alias cls='clear; l'

# Navigation {{{1
# ==============================================================================

# Navigate up parent directories without 'cd'.
if ! _koopa_is_installed autojump
then
    alias ..='cd ..'
    alias ...='cd ../../'
    alias ....='cd ../../../'
    alias .....='cd ../../../../'
    alias ......='cd ../../../../../'
fi

# Browse up and down.
alias u='clear; cd ../; pwd; l'
alias d='clear; cd -; l'

# Programs {{{1
# ==============================================================================

# black {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed black
then
    # Note that 79 characters conforms to PEP8 (see flake8 for details).
    alias black='black --line-length=79'
fi

# cmus {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed cmus
then
    alias cmus='cmus --listen 127.0.0.1'
fi

# Emacs {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed emacs
then
    if [ -f "${HOME}/.terminfo/78/xterm-24bit" ]
    then
        alias emacs='TERM=xterm-24bit emacs --no-window-system'
    else
        alias emacs='emacs --no-window-system'
    fi
    alias emacs-vanilla='emacs --no-init-file --no-window-system'
fi

# Git {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed git
then
    alias develop='git fetch; git checkout develop; git branch -vv'
    alias main='git fetch; git checkout main; git branch -vv'
    alias master='git fetch; git checkout master; git branch -vv'
fi

# Python {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed python3
then
    alias python='python3'
fi

# R {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed R
then
    alias R='R --no-restore --no-save --quiet'
fi

# ripgrep {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed rg
then
    alias rg-fixme="rg -il 'FIXME' | sort"
    alias rg-sort='rg --pretty --sort path'
fi

# ronn {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed ronn
then
    alias ronn='ronn --roff'
fi

# shasum {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed shasum
then
    alias sha256='shasum -a 256'
fi

# tar {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed tar
then
    alias tar-c='tar -czvf'
    alias tar-x='tar -xzvf'
fi

# Vim {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed nvim
then
    alias nvim-vanilla='unalias nvim; nvim -u NONE'
    # > alias {vi,vim}='nvim'
fi
if _koopa_is_installed vim
then
    alias vim-vanilla='unalias vim; vim -i NONE -u NONE -U NONE'
    alias vi='vim'
fi

# zoxide {{{2
# ------------------------------------------------------------------------------

# Fix for autojump muscle memory, using zoxide.
if _koopa_is_installed zoxide && ! _koopa_is_installed autojump
then
    alias j='z'
fi

# macOS {{{1
# ==============================================================================

if _koopa_is_macos
then
    # Lock the screen (when going AFK).
    alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
    # Hide a file or folder from appearing in the Finder.
    alias finder-hide='setfile -a V'
    # Check iCloud sync status.
    alias icloud-status='brctl log --wait --shorten'
    # Search using Spotlight index, instead of GNU find.
    alias locate='mdfind -name'
    # Often PlistBuddy is more useful than 'defaults'.
    alias plistbuddy='/usr/libexec/PlistBuddy'
    # Reload autofs mounts defined in '/etc/auto_master' (and '/etc/auto_nfs').
    alias reload-mounts='sudo automount -vc'

    # Navigation shortcuts {{{2
    # --------------------------------------------------------------------------
    alias dl='cd ~/Downloads; l'
    alias docs='cd ~/Documents; l'

    # GUI applications {{{2
    # --------------------------------------------------------------------------
    alias canary='open -a "google chrome canary"'
    alias chrome='open -a "google chrome"'
    alias firefox='open -a firefox'
    alias homebrew-cask='cd "$(brew --repo homebrew/cask)"'
    alias homebrew-core='cd "$(brew --repo homebrew/core)"'
    alias rstudio='open -a rstudio'
    alias safari='open -a safari'

    # Volume control {{{2
    # --------------------------------------------------------------------------
    # > alias vol100='osascript -e "set volume output volume 100"'
    alias mute='osascript -e "set volume output muted true"'
fi
