#!/bin/sh

# """
# POSIX aliases.
# @note Updated 2021-06-08.
# """

# Shortcuts {{{1
# ==============================================================================

alias :q='exit'
alias c='clear'
alias e='exit'
alias h='history'
alias q='exit'

# Listing files {{{1
# ==============================================================================

if _koopa_is_installed 'exa'
then
    # Use exa instead of ls, when possible.
    # https://the.exa.website/docs/command-line-options
    #
    # Useful exa flags:
    # * -F, --classify
    #         Displays file type indicators by file names.
    # * -a, --all
    #         Shows hidden and ‘dot’ files.
    #         Use this twice to also show the . and .. directories.
    # * -g, --group
    #         Lists each file’s group.
    # * -l, --long
    #         Displays files in a table along with their metadata.
    # * -s, --sort=SORT_FIELD
    #         Configures which field to sort by.
    # *     --git-ignore
    #         Ignores files mentioned in .gitignore.
    # *     --group-directories-first
    #         Lists directories before other files when sorting.
    alias l="exa  --classify --group --group-directories-first --sort='Name'"
    alias la='l --all'
    alias ll='la --long'
else
    # Otherwise fall back to system ls.
    #
    # Note that note all versions of ls support long flags.
    #
    # Useful ls flags:
    # * -B, --ignore-backups
    #         do not list implied entries ending with ~
    # * -F, --classify
    #         append indicator (one of */=>@|) to entries
    # * -h, --human-readable
    #         with -l and -s, print sizes like 1K 234M 2G etc.
    alias l='ls -BFh'
    alias la='l -a'
    alias ll='la -l'
fi
alias l.='l -d .*'
alias l1='ls -1'

# List head or tail.
alias lh='l | head'
alias lt='l | tail'

# Navigation {{{1
# ==============================================================================

# Navigate up parent directories without 'cd'.
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'

# Browse up and down.
alias u='clear; cd ../; pwd; l'
alias d='clear; cd -; l'

# Programs {{{1
# ==============================================================================

# black {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed 'black'
then
    # Note that 79 characters conforms to PEP8 (see flake8 for details).
    alias black='black --line-length=79'
fi

# broot {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed 'broot'
then
    alias br-size='br --sort-by-size'
fi

# Python {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed 'python3'
then
    alias python='python3'
fi

# R {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed 'R'
then
    alias R='R --no-restore --no-save --quiet'
fi

# ronn {{{2
# ------------------------------------------------------------------------------

if _koopa_is_installed 'ronn'
then
    alias ronn='ronn --roff'
fi
