#!/bin/sh

__koopa_activate_user_profile() { # {{{1
    # """
    # Activate koopa shell for current user.
    # @note Updated 2021-05-25.
    # @seealso https://koopa.acidgenomics.com/
    # """
    export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
    if [ -f "${XDG_CONFIG_HOME}/koopa/activate" ]
    then
        # > export KOOPA_MINIMAL=1
        # > export KOOPA_TEST=1
        # > export KOOPA_USERS_SKIP='mike'
        # shellcheck source=/dev/null
        . "${XDG_CONFIG_HOME}/koopa/activate"
    fi
    return 0
}

__koopa_activate_user_profile
