# Source public profile scripts.
for file in "${HOME}/.dotfiles/macOS/bash/login/"*; do
    source "$file"
done

# Source private profile scripts.
for file in "${HOME}/.dotfiles-private/macOS/bash/login/"*; do
    source "$file"
done

unset -v file
