# """
# Homebrew Bundle Brewfile.
# Updated 2020-11-10.
#
# Problematic formulas:
# - armadillo
# - imagemagick
# - lapack
# - libiconv
# - libressl
#
# Large formulas:
# - gcc
# - llvm (use LLVM's Debian APT instead)
#
# Formula without bottles:
# - gdal
# - mariadb-connector-c
# """

brew "python@3.9", link: false

brew "ack"
brew "autoconf"
brew "autojump"
brew "automake"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bash-completion"
brew "bat"  # rust
brew "bfg"
brew "binutils"
brew "black"  # python
brew "broot"  # rust
brew "ccache"
brew "checkbashisms"
brew "circleci"
brew "cmake"
brew "cmus"
brew "convmv"
brew "coreutils"
brew "curl"
brew "dash"
brew "dog"  # rust
brew "dust"  # rust
brew "exa"  # rust
brew "fd"  # rust
brew "findutils"
brew "fish"
brew "flake8"  # python
brew "fzf"
brew "gawk"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-units"
brew "gnu-which"
brew "go"
brew "gpatch"
brew "grep"
brew "groff"
brew "gsl"
brew "hdf5"
brew "htop"
brew "igraph"
brew "jq"
brew "leiningen"
brew "lesspipe"
brew "lua"
brew "luarocks"
brew "make"
brew "man-db"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "open-mpi"
brew "openblas"
brew "openssh"
brew "pandoc"
brew "pandoc-citeproc"
brew "pandoc-crossref"
brew "parallel"
brew "pass"
brew "pcre"
brew "pkg-config"
brew "podofo"
brew "procs"  # rust
brew "proj"
brew "protobuf"
brew "pylint"  # python
brew "ranger"  # python
brew "rename"
brew "ripgrep"  # rust
brew "rsync"
brew "ruby"
brew "screen"
brew "shellcheck"
brew "shellharden"
brew "shunit2"
brew "sqlite"
brew "starship"  # rust
brew "subversion"
brew "taglib"
brew "tcl-tk"
brew "tcsh"
brew "tesseract"
brew "texinfo"
brew "tmux"
brew "tokei"  # rust
brew "trash"
brew "udunits"
brew "v8"
brew "vim"
brew "wget"
brew "xsv"  # rust
brew "zlib"
brew "zoxide"  # rust
brew "zsh"
