#!/usr/bin/env zsh

# """
# .zshrc: Always read for an interactive shell, whether it's a login one or not.
#
# Debug with:
# - bindkey
# - setopt
#
# See also:
# - http://zsh.sourceforge.net/Doc/Release/Completion-System.html
# - http://zsh.sourceforge.net/Doc/Release/Options.html
# - http://zsh.sourceforge.net/Doc/Release/Options.html#index-MARKDIRS
# - http://zsh.sourceforge.net/Doc/Release/Options.html#index-NOMARKDIRS
# - http://zsh.sourceforge.net/Guide/zshguide06.html
# - https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/completion.zsh
# """

source "${HOME}/.profile"

setopt_array=(
    # auto_menu                 # completion
    # auto_name_dirs            # dirs
    # complete_aliases          # completion
    # extended_glob             # glob
    always_to_end               # completion
    append_history              # history
    auto_cd                     # dirs
    auto_pushd                  # dirs
    complete_in_word            # completion
    extended_history            # history
    hist_expire_dups_first      # history
    hist_ignore_dups            # history
    hist_ignore_space           # history
    hist_verify                 # history
    inc_append_history          # history
    interactive_comments        # misc
    long_list_jobs              # jobs
    pushd_ignore_dups           # dirs
    pushd_minus                 # dirs
    share_history               # history
)
setopt "${setopt_array[@]}"
unset -v setopt_array

unsetopt_array=(
    bang_hist
    flow_control
)
unsetopt "${unsetopt_array[@]}"
unset -v unsetopt_array

# Fix the delete key.
bindkey "\e[3~" delete-char

# Set the autosuggest text color.
# Define using xterm-256 color code.
#
# 'fg=240' also works well with Dracula theme.
#
# See also:
# - https://stackoverflow.com/questions/47310537
# - https://upload.wikimedia.org/wikipedia/
#       commons/1/15/Xterm_256color_chart.svg
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=005"
